// Generated by CoffeeScript 1.6.1
(function() {
  var Artist, ObjectId, Order, Wager, findAlbumForSong, findSong, logger, mongoose, _;

  logger = require('winston');

  Order = require('../repositories/order').Order;

  Wager = require('../repositories/wager').Wager;

  Artist = require('../repositories/artist').Artist;

  mongoose = require('mongoose');

  _ = require('underscore');

  ObjectId = mongoose.Types.ObjectId;

  exports.artistCreated = function(event) {
    var artist;
    logger.debug(event);
    artist = new Artist(event.payload);
    return artist.save(function(err) {
      if (err) {
        logger.error("Error creating Artist: " + err);
      }
      return logger.info("Artist Created");
    });
  };

  exports.albumAdded = function(event) {
    logger.debug(event);
    return Artist.findOne({
      _id: event.payload.id
    }, function(err, artist) {
      var newAlbum;
      if (err) {
        logger.error("error searching for artist: " + err);
      }
      if (artist) {
        logger.debug("adding album: " + JSON.stringify(event.payload) + "to artistId: " + artist._id);
        newAlbum = {
          _id: event.payload.albumId,
          name: event.payload.name,
          description: event.payload.description,
          price: event.payload.price,
          offerDate: event.payload.offerDate,
          isActiveOffer: event.payload.isActiveOffer,
          offerId: event.payload.offerId
        };
        artist.albums.push(newAlbum);
        return artist.save(function(err) {
          if (err) {
            logger.error("Error adding album: " + err);
          }
          return logger.info("Album Saved");
        });
      } else {
        return logger.error("Artist for not found for event: " + JSON.stringify(event.payload));
      }
    });
  };

  exports.albumUpdated = function(event) {
    logger.debug(event);
    return Artist.findOne({
      "albums._id": event.payload.itemId
    }, function(err, artist) {
      var album, newFields, updatedAlbum;
      if (err) {
        logger.error("Error updating album: " + err);
      }
      if (artist) {
        album = _.find(artist.albums, function(album) {
          return album._id.toString() === event.payload.itemId;
        });
        newFields = _.omit(event.payload, "id");
        updatedAlbum = _.extend(album, newFields);
        return artist.save(function(err, artist) {
          if (err) {
            return logger.error("Error updating artist" + err);
          }
        });
      } else {
        return logger.error("Artist Not Found");
      }
    });
  };

  exports.songAddedToAlbum = function(event) {
    return Artist.findOne({
      "albums._id": event.payload.albumId
    }, function(err, artist) {
      var theAlbum;
      if (err) {
        logger.error("Error finding artist/album");
      }
      if (artist) {
        theAlbum = _.find(artist.albums, function(album) {
          return album._id.toString() === event.payload.albumId;
        });
        theAlbum.songs.push(event.payload.song);
        return artist.save(function(err, artist) {
          if (err) {
            return logger.error("Error updating artist: " + err);
          }
        });
      } else {
        return logger.info("Artist not found");
      }
    });
  };

  findAlbumForSong = function(albums, itemId) {
    return _.find(albums, function(album) {
      return _.find(album.songs, function(song) {
        return song.itemId === itemId;
      });
    });
  };

  findSong = function(songs, itemId) {
    return _.find(songs, function(song) {
      return song.itemId === itemId;
    });
  };

  exports.songUpdated = function(event) {
    logger.debug(JSON.stringify(event));
    return Artist.findOne({
      "albums.songs.itemId": event.payload.itemId
    }, function(err, artist) {
      var album, eventData, song, updatedSong;
      if (err) {
        logger.error("Error/finding artist album for event: " + event);
      }
      logger.debug(JSON.stringify(artist));
      album = findAlbumForSong(artist.albums, event.payload.itemId);
      song = findSong(album.songs, event.payload.itemId);
      eventData = _.omit(event.payload, ['itemId']);
      updatedSong = _.extend(song, eventData);
      artist.save(function(err) {
        if (err) {
          return logger.error("Error saving artist for event: " + event);
        }
      });
      return logger.debug(album);
    });
  };

}).call(this);
